//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.detalleFactura = new HashSet<detalleFactura>();
        }
    
        public int idFactura { get; set; }
        public int idUsuario { get; set; }
        public int idTienda { get; set; }
        public string fecha { get; set; }
        public double totalPagado { get; set; }
        public int idTipoSalida { get; set; }
        public string comentario { get; set; }
    
        public virtual tienda tienda { get; set; }
        public virtual tipoSalida tipoSalida { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleFactura> detalleFactura { get; set; }
    }
}
