//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingreso
    {
        public int id { get; set; }
        public int idProveedor { get; set; }
        public int idEstante { get; set; }
        public int idTipoIngreso { get; set; }
        public int idProducto { get; set; }
        public int cantidadIngreso { get; set; }
        public string comentario { get; set; }
    
        public virtual estante estante { get; set; }
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual tipoIngreso tipoIngreso { get; set; }
    }
}
