//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(InventarioMetadata))]

    public partial class inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventario()
        {
            this.detalleFactura = new HashSet<detalleFactura>();
        }
    
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idTienda { get; set; }
        public string fecha { get; set; }
        public Nullable<double> totalPagado { get; set; }
        public string comentario { get; set; }
        public Nullable<double> iva { get; set; }
        public int idTipoMovimiento { get; set; }
    
        public virtual tienda tienda { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleFactura> detalleFactura { get; set; }
    }
}
